//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace FaceBookNuker.Models
{
    [Serializable]
    public partial class M_Account
    {
        public int Pid { get; set; }
        public string Name { get; set; }
        public string Pass { get; set; }
        public string Email { get; set; }
    }
    
}
