#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuaThuThanh.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tinphuong_com_db")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertM_Tuong(M_Tuong instance);
    partial void UpdateM_Tuong(M_Tuong instance);
    partial void DeleteM_Tuong(M_Tuong instance);
    partial void InsertM_BoTuong(M_BoTuong instance);
    partial void UpdateM_BoTuong(M_BoTuong instance);
    partial void DeleteM_BoTuong(M_BoTuong instance);
    partial void InsertM_Nuoc(M_Nuoc instance);
    partial void UpdateM_Nuoc(M_Nuoc instance);
    partial void DeleteM_Nuoc(M_Nuoc instance);
    partial void InsertM_Phai(M_Phai instance);
    partial void UpdateM_Phai(M_Phai instance);
    partial void DeleteM_Phai(M_Phai instance);
    partial void InsertM_TuyetKy(M_TuyetKy instance);
    partial void UpdateM_TuyetKy(M_TuyetKy instance);
    partial void DeleteM_TuyetKy(M_TuyetKy instance);
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["tinphuong_com_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<M_Tuong> M_Tuongs
		{
			get
			{
				return this.GetTable<M_Tuong>();
			}
		}
		
		public System.Data.Linq.Table<M_BoTuong> M_BoTuongs
		{
			get
			{
				return this.GetTable<M_BoTuong>();
			}
		}
		
		public System.Data.Linq.Table<M_Nuoc> M_Nuocs
		{
			get
			{
				return this.GetTable<M_Nuoc>();
			}
		}
		
		public System.Data.Linq.Table<M_Phai> M_Phais
		{
			get
			{
				return this.GetTable<M_Phai>();
			}
		}
		
		public System.Data.Linq.Table<M_TuyetKy> M_TuyetKies
		{
			get
			{
				return this.GetTable<M_TuyetKy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="vtt.M_Tuong")]
	public partial class M_Tuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pid;
		
		private string _MaTuong;
		
		private string _TenTuong;
		
		private System.Nullable<int> _SoSao;
		
		private System.Nullable<int> _NuocXid;
		
		private System.Nullable<int> _PhaiXid;
		
		private System.Nullable<int> _LucDanh;
		
		private System.Nullable<int> _TamDanh;
		
		private System.Nullable<int> _TocDoDanh;
		
		private System.Nullable<int> _Mau;
		
		private System.Nullable<int> _TriLuc;
		
		private System.Nullable<int> _TocDoDiChuyen;
		
		private System.Nullable<int> _TuyetKy1Xid;
		
		private System.Nullable<int> _TuyetKy2Xid;
		
		private System.Nullable<int> _BoTuongXid;
		
		private EntityRef<M_BoTuong> _M_BoTuong;
		
		private EntityRef<M_Nuoc> _M_Nuoc;
		
		private EntityRef<M_Phai> _M_Phai;
		
		private EntityRef<M_TuyetKy> _M_TuyetKy;
		
		private EntityRef<M_TuyetKy> _M_TuyetKy1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnMaTuongChanging(string value);
    partial void OnMaTuongChanged();
    partial void OnTenTuongChanging(string value);
    partial void OnTenTuongChanged();
    partial void OnSoSaoChanging(System.Nullable<int> value);
    partial void OnSoSaoChanged();
    partial void OnNuocXidChanging(System.Nullable<int> value);
    partial void OnNuocXidChanged();
    partial void OnPhaiXidChanging(System.Nullable<int> value);
    partial void OnPhaiXidChanged();
    partial void OnLucDanhChanging(System.Nullable<int> value);
    partial void OnLucDanhChanged();
    partial void OnTamDanhChanging(System.Nullable<int> value);
    partial void OnTamDanhChanged();
    partial void OnTocDoDanhChanging(System.Nullable<int> value);
    partial void OnTocDoDanhChanged();
    partial void OnMauChanging(System.Nullable<int> value);
    partial void OnMauChanged();
    partial void OnTriLucChanging(System.Nullable<int> value);
    partial void OnTriLucChanged();
    partial void OnTocDoDiChuyenChanging(System.Nullable<int> value);
    partial void OnTocDoDiChuyenChanged();
    partial void OnTuyetKy1XidChanging(System.Nullable<int> value);
    partial void OnTuyetKy1XidChanged();
    partial void OnTuyetKy2XidChanging(System.Nullable<int> value);
    partial void OnTuyetKy2XidChanged();
    partial void OnBoTuongXidChanging(System.Nullable<int> value);
    partial void OnBoTuongXidChanged();
    #endregion
		
		public M_Tuong()
		{
			this._M_BoTuong = default(EntityRef<M_BoTuong>);
			this._M_Nuoc = default(EntityRef<M_Nuoc>);
			this._M_Phai = default(EntityRef<M_Phai>);
			this._M_TuyetKy = default(EntityRef<M_TuyetKy>);
			this._M_TuyetKy1 = default(EntityRef<M_TuyetKy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTuong", DbType="VarChar(MAX)")]
		public string MaTuong
		{
			get
			{
				return this._MaTuong;
			}
			set
			{
				if ((this._MaTuong != value))
				{
					this.OnMaTuongChanging(value);
					this.SendPropertyChanging();
					this._MaTuong = value;
					this.SendPropertyChanged("MaTuong");
					this.OnMaTuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTuong", DbType="NVarChar(MAX)")]
		public string TenTuong
		{
			get
			{
				return this._TenTuong;
			}
			set
			{
				if ((this._TenTuong != value))
				{
					this.OnTenTuongChanging(value);
					this.SendPropertyChanging();
					this._TenTuong = value;
					this.SendPropertyChanged("TenTuong");
					this.OnTenTuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSao", DbType="Int")]
		public System.Nullable<int> SoSao
		{
			get
			{
				return this._SoSao;
			}
			set
			{
				if ((this._SoSao != value))
				{
					this.OnSoSaoChanging(value);
					this.SendPropertyChanging();
					this._SoSao = value;
					this.SendPropertyChanged("SoSao");
					this.OnSoSaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NuocXid", DbType="Int")]
		public System.Nullable<int> NuocXid
		{
			get
			{
				return this._NuocXid;
			}
			set
			{
				if ((this._NuocXid != value))
				{
					if (this._M_Nuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNuocXidChanging(value);
					this.SendPropertyChanging();
					this._NuocXid = value;
					this.SendPropertyChanged("NuocXid");
					this.OnNuocXidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhaiXid", DbType="Int")]
		public System.Nullable<int> PhaiXid
		{
			get
			{
				return this._PhaiXid;
			}
			set
			{
				if ((this._PhaiXid != value))
				{
					if (this._M_Phai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhaiXidChanging(value);
					this.SendPropertyChanging();
					this._PhaiXid = value;
					this.SendPropertyChanged("PhaiXid");
					this.OnPhaiXidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LucDanh", DbType="Int")]
		public System.Nullable<int> LucDanh
		{
			get
			{
				return this._LucDanh;
			}
			set
			{
				if ((this._LucDanh != value))
				{
					this.OnLucDanhChanging(value);
					this.SendPropertyChanging();
					this._LucDanh = value;
					this.SendPropertyChanged("LucDanh");
					this.OnLucDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamDanh", DbType="Int")]
		public System.Nullable<int> TamDanh
		{
			get
			{
				return this._TamDanh;
			}
			set
			{
				if ((this._TamDanh != value))
				{
					this.OnTamDanhChanging(value);
					this.SendPropertyChanging();
					this._TamDanh = value;
					this.SendPropertyChanged("TamDanh");
					this.OnTamDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TocDoDanh", DbType="Int")]
		public System.Nullable<int> TocDoDanh
		{
			get
			{
				return this._TocDoDanh;
			}
			set
			{
				if ((this._TocDoDanh != value))
				{
					this.OnTocDoDanhChanging(value);
					this.SendPropertyChanging();
					this._TocDoDanh = value;
					this.SendPropertyChanged("TocDoDanh");
					this.OnTocDoDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mau", DbType="Int")]
		public System.Nullable<int> Mau
		{
			get
			{
				return this._Mau;
			}
			set
			{
				if ((this._Mau != value))
				{
					this.OnMauChanging(value);
					this.SendPropertyChanging();
					this._Mau = value;
					this.SendPropertyChanged("Mau");
					this.OnMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TriLuc", DbType="Int")]
		public System.Nullable<int> TriLuc
		{
			get
			{
				return this._TriLuc;
			}
			set
			{
				if ((this._TriLuc != value))
				{
					this.OnTriLucChanging(value);
					this.SendPropertyChanging();
					this._TriLuc = value;
					this.SendPropertyChanged("TriLuc");
					this.OnTriLucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TocDoDiChuyen", DbType="Int")]
		public System.Nullable<int> TocDoDiChuyen
		{
			get
			{
				return this._TocDoDiChuyen;
			}
			set
			{
				if ((this._TocDoDiChuyen != value))
				{
					this.OnTocDoDiChuyenChanging(value);
					this.SendPropertyChanging();
					this._TocDoDiChuyen = value;
					this.SendPropertyChanged("TocDoDiChuyen");
					this.OnTocDoDiChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuyetKy1Xid", DbType="Int")]
		public System.Nullable<int> TuyetKy1Xid
		{
			get
			{
				return this._TuyetKy1Xid;
			}
			set
			{
				if ((this._TuyetKy1Xid != value))
				{
					if (this._M_TuyetKy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTuyetKy1XidChanging(value);
					this.SendPropertyChanging();
					this._TuyetKy1Xid = value;
					this.SendPropertyChanged("TuyetKy1Xid");
					this.OnTuyetKy1XidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuyetKy2Xid", DbType="Int")]
		public System.Nullable<int> TuyetKy2Xid
		{
			get
			{
				return this._TuyetKy2Xid;
			}
			set
			{
				if ((this._TuyetKy2Xid != value))
				{
					if (this._M_TuyetKy1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTuyetKy2XidChanging(value);
					this.SendPropertyChanging();
					this._TuyetKy2Xid = value;
					this.SendPropertyChanged("TuyetKy2Xid");
					this.OnTuyetKy2XidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoTuongXid", DbType="Int")]
		public System.Nullable<int> BoTuongXid
		{
			get
			{
				return this._BoTuongXid;
			}
			set
			{
				if ((this._BoTuongXid != value))
				{
					if (this._M_BoTuong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBoTuongXidChanging(value);
					this.SendPropertyChanging();
					this._BoTuongXid = value;
					this.SendPropertyChanged("BoTuongXid");
					this.OnBoTuongXidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_BoTuong_M_Tuong", Storage="_M_BoTuong", ThisKey="BoTuongXid", OtherKey="Pid", IsForeignKey=true)]
		public M_BoTuong M_BoTuong
		{
			get
			{
				return this._M_BoTuong.Entity;
			}
			set
			{
				M_BoTuong previousValue = this._M_BoTuong.Entity;
				if (((previousValue != value) 
							|| (this._M_BoTuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._M_BoTuong.Entity = null;
						previousValue.M_Tuongs.Remove(this);
					}
					this._M_BoTuong.Entity = value;
					if ((value != null))
					{
						value.M_Tuongs.Add(this);
						this._BoTuongXid = value.Pid;
					}
					else
					{
						this._BoTuongXid = default(Nullable<int>);
					}
					this.SendPropertyChanged("M_BoTuong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_Nuoc_M_Tuong", Storage="_M_Nuoc", ThisKey="NuocXid", OtherKey="Pid", IsForeignKey=true)]
		public M_Nuoc M_Nuoc
		{
			get
			{
				return this._M_Nuoc.Entity;
			}
			set
			{
				M_Nuoc previousValue = this._M_Nuoc.Entity;
				if (((previousValue != value) 
							|| (this._M_Nuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._M_Nuoc.Entity = null;
						previousValue.M_Tuongs.Remove(this);
					}
					this._M_Nuoc.Entity = value;
					if ((value != null))
					{
						value.M_Tuongs.Add(this);
						this._NuocXid = value.Pid;
					}
					else
					{
						this._NuocXid = default(Nullable<int>);
					}
					this.SendPropertyChanged("M_Nuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_Phai_M_Tuong", Storage="_M_Phai", ThisKey="PhaiXid", OtherKey="Pid", IsForeignKey=true)]
		public M_Phai M_Phai
		{
			get
			{
				return this._M_Phai.Entity;
			}
			set
			{
				M_Phai previousValue = this._M_Phai.Entity;
				if (((previousValue != value) 
							|| (this._M_Phai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._M_Phai.Entity = null;
						previousValue.M_Tuongs.Remove(this);
					}
					this._M_Phai.Entity = value;
					if ((value != null))
					{
						value.M_Tuongs.Add(this);
						this._PhaiXid = value.Pid;
					}
					else
					{
						this._PhaiXid = default(Nullable<int>);
					}
					this.SendPropertyChanged("M_Phai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_TuyetKy_M_Tuong", Storage="_M_TuyetKy", ThisKey="TuyetKy1Xid", OtherKey="Pid", IsForeignKey=true)]
		public M_TuyetKy M_TuyetKy
		{
			get
			{
				return this._M_TuyetKy.Entity;
			}
			set
			{
				M_TuyetKy previousValue = this._M_TuyetKy.Entity;
				if (((previousValue != value) 
							|| (this._M_TuyetKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._M_TuyetKy.Entity = null;
						previousValue.M_Tuongs.Remove(this);
					}
					this._M_TuyetKy.Entity = value;
					if ((value != null))
					{
						value.M_Tuongs.Add(this);
						this._TuyetKy1Xid = value.Pid;
					}
					else
					{
						this._TuyetKy1Xid = default(Nullable<int>);
					}
					this.SendPropertyChanged("M_TuyetKy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_TuyetKy_M_Tuong1", Storage="_M_TuyetKy1", ThisKey="TuyetKy2Xid", OtherKey="Pid", IsForeignKey=true)]
		public M_TuyetKy M_TuyetKy1
		{
			get
			{
				return this._M_TuyetKy1.Entity;
			}
			set
			{
				M_TuyetKy previousValue = this._M_TuyetKy1.Entity;
				if (((previousValue != value) 
							|| (this._M_TuyetKy1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._M_TuyetKy1.Entity = null;
						previousValue.M_Tuongs1.Remove(this);
					}
					this._M_TuyetKy1.Entity = value;
					if ((value != null))
					{
						value.M_Tuongs1.Add(this);
						this._TuyetKy2Xid = value.Pid;
					}
					else
					{
						this._TuyetKy2Xid = default(Nullable<int>);
					}
					this.SendPropertyChanged("M_TuyetKy1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="vtt.M_BoTuong")]
	public partial class M_BoTuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pid;
		
		private string _BoTuong;
		
		private EntitySet<M_Tuong> _M_Tuongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnBoTuongChanging(string value);
    partial void OnBoTuongChanged();
    #endregion
		
		public M_BoTuong()
		{
			this._M_Tuongs = new EntitySet<M_Tuong>(new Action<M_Tuong>(this.attach_M_Tuongs), new Action<M_Tuong>(this.detach_M_Tuongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoTuong", DbType="NVarChar(MAX)")]
		public string BoTuong
		{
			get
			{
				return this._BoTuong;
			}
			set
			{
				if ((this._BoTuong != value))
				{
					this.OnBoTuongChanging(value);
					this.SendPropertyChanging();
					this._BoTuong = value;
					this.SendPropertyChanged("BoTuong");
					this.OnBoTuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_BoTuong_M_Tuong", Storage="_M_Tuongs", ThisKey="Pid", OtherKey="BoTuongXid")]
		public EntitySet<M_Tuong> M_Tuongs
		{
			get
			{
				return this._M_Tuongs;
			}
			set
			{
				this._M_Tuongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_M_Tuongs(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_BoTuong = this;
		}
		
		private void detach_M_Tuongs(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_BoTuong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="vtt.M_Nuoc")]
	public partial class M_Nuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pid;
		
		private string _Nuoc;
		
		private EntitySet<M_Tuong> _M_Tuongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnNuocChanging(string value);
    partial void OnNuocChanged();
    #endregion
		
		public M_Nuoc()
		{
			this._M_Tuongs = new EntitySet<M_Tuong>(new Action<M_Tuong>(this.attach_M_Tuongs), new Action<M_Tuong>(this.detach_M_Tuongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nuoc", DbType="NVarChar(MAX)")]
		public string Nuoc
		{
			get
			{
				return this._Nuoc;
			}
			set
			{
				if ((this._Nuoc != value))
				{
					this.OnNuocChanging(value);
					this.SendPropertyChanging();
					this._Nuoc = value;
					this.SendPropertyChanged("Nuoc");
					this.OnNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_Nuoc_M_Tuong", Storage="_M_Tuongs", ThisKey="Pid", OtherKey="NuocXid")]
		public EntitySet<M_Tuong> M_Tuongs
		{
			get
			{
				return this._M_Tuongs;
			}
			set
			{
				this._M_Tuongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_M_Tuongs(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_Nuoc = this;
		}
		
		private void detach_M_Tuongs(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_Nuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="vtt.M_Phai")]
	public partial class M_Phai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pid;
		
		private string _Phai;
		
		private EntitySet<M_Tuong> _M_Tuongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnPhaiChanging(string value);
    partial void OnPhaiChanged();
    #endregion
		
		public M_Phai()
		{
			this._M_Tuongs = new EntitySet<M_Tuong>(new Action<M_Tuong>(this.attach_M_Tuongs), new Action<M_Tuong>(this.detach_M_Tuongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phai", DbType="NVarChar(MAX)")]
		public string Phai
		{
			get
			{
				return this._Phai;
			}
			set
			{
				if ((this._Phai != value))
				{
					this.OnPhaiChanging(value);
					this.SendPropertyChanging();
					this._Phai = value;
					this.SendPropertyChanged("Phai");
					this.OnPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_Phai_M_Tuong", Storage="_M_Tuongs", ThisKey="Pid", OtherKey="PhaiXid")]
		public EntitySet<M_Tuong> M_Tuongs
		{
			get
			{
				return this._M_Tuongs;
			}
			set
			{
				this._M_Tuongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_M_Tuongs(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_Phai = this;
		}
		
		private void detach_M_Tuongs(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_Phai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="vtt.M_TuyetKy")]
	public partial class M_TuyetKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pid;
		
		private string _TuyetKy;
		
		private string _MoTa;
		
		private EntitySet<M_Tuong> _M_Tuongs;
		
		private EntitySet<M_Tuong> _M_Tuongs1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPidChanging(int value);
    partial void OnPidChanged();
    partial void OnTuyetKyChanging(string value);
    partial void OnTuyetKyChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public M_TuyetKy()
		{
			this._M_Tuongs = new EntitySet<M_Tuong>(new Action<M_Tuong>(this.attach_M_Tuongs), new Action<M_Tuong>(this.detach_M_Tuongs));
			this._M_Tuongs1 = new EntitySet<M_Tuong>(new Action<M_Tuong>(this.attach_M_Tuongs1), new Action<M_Tuong>(this.detach_M_Tuongs1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuyetKy", DbType="NVarChar(MAX)")]
		public string TuyetKy
		{
			get
			{
				return this._TuyetKy;
			}
			set
			{
				if ((this._TuyetKy != value))
				{
					this.OnTuyetKyChanging(value);
					this.SendPropertyChanging();
					this._TuyetKy = value;
					this.SendPropertyChanged("TuyetKy");
					this.OnTuyetKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_TuyetKy_M_Tuong", Storage="_M_Tuongs", ThisKey="Pid", OtherKey="TuyetKy1Xid")]
		public EntitySet<M_Tuong> M_Tuongs
		{
			get
			{
				return this._M_Tuongs;
			}
			set
			{
				this._M_Tuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="M_TuyetKy_M_Tuong1", Storage="_M_Tuongs1", ThisKey="Pid", OtherKey="TuyetKy2Xid")]
		public EntitySet<M_Tuong> M_Tuongs1
		{
			get
			{
				return this._M_Tuongs1;
			}
			set
			{
				this._M_Tuongs1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_M_Tuongs(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_TuyetKy = this;
		}
		
		private void detach_M_Tuongs(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_TuyetKy = null;
		}
		
		private void attach_M_Tuongs1(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_TuyetKy1 = this;
		}
		
		private void detach_M_Tuongs1(M_Tuong entity)
		{
			this.SendPropertyChanging();
			entity.M_TuyetKy1 = null;
		}
	}
}
#pragma warning restore 1591
