//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace FaceBookNuker.Models
{
    public partial class PostStatus
    {
        public int ID { get; set; }
        public Nullable<int> FaceBookID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string StatusContent { get; set; }
    }
    
}
